In [1]:
import pandas
import numpy as np

In [12]:
pathway_data = pandas.read_csv('/data4/mankovic/ZOETIS/felis_catus_pathways.csv', index_col = 0)

In [20]:
pathway_data = pathway_data.fillna(0)

In [21]:
ii=0
for index, row in pathway_data.iterrows():
    if ii > 0:
        break
    print(index)
    print(row)
    ii+=1

R-HSA-162699
A1BG           0.0
A1CF           0.0
A2ML1          0.0
A2M            0.0
A3GALT2        0.0
              ... 
NKX6.2         0.0
NKX6.3         0.0
TRNAY.GUA_5    0.0
MARC1          0.0
MARC2          0.0
Name: R-HSA-162699, Length: 35607, dtype: float64


Index(['ALPI', 'ALPL', 'ART3', 'ART4', 'BST1', 'CD109', 'CNTN3', 'CNTN4',
       'CNTN5', 'CPM', 'DPM1', 'DPM2', 'DPM3', 'FCGR3A', 'GP2', 'GPAA1',
       'GPIHBP1', 'GPLD1', 'IZUMO1R', 'LOC101084733', 'LOC101086271',
       'LOC101091333', 'LOC101096984', 'LSAMP', 'LY6D', 'LY6G6C', 'LY6H',
       'LYPD1', 'LYPD2', 'LYPD3', 'LYPD4', 'LYPD5', 'LYPD6B', 'LYPD8', 'MDGA1',
       'MDGA2', 'MELTF', 'NEGR1', 'NRN1L', 'NRN1', 'NTM', 'NTNG1', 'NTNG2',
       'OPCML', 'OTOA', 'PGAP1', 'PIGA', 'PIGB', 'PIGC', 'PIGF', 'PIGG',
       'PIGH', 'PIGK', 'PIGL', 'PIGM', 'PIGN', 'PIGO', 'PIGP', 'PIGQ', 'PIGS',
       'PIGT', 'PIGU', 'PIGV', 'PIGW', 'PIGX', 'PIGY', 'PLAUR', 'PLET1',
       'PRND', 'PSCA', 'RECK', 'RTN4RL1', 'RTN4RL2', 'SPACA4', 'TECTA',
       'TECTB', 'TEX101', 'THY1', 'XPNPEP2'],
      dtype='object')

In [16]:

mask = row.gt(0.0).values
features_in_pathway = cols[mask].tolist()

AttributeError: 'Series' object has no attribute 'columns'

In [2]:
A = np.abs(np.random.rand(20,20))

In [3]:
A = A - np.diag(A)
A = A + A.T

In [4]:
A[:,1] = 0
A[:,5] = 0
A[1,:] = 0
A[5,:] = 0
A

array([[ 0.        ,  0.        , -0.01808192, -0.60828747, -0.38430035,
         0.        , -0.37013991,  0.11947516, -0.37239082,  0.44627565,
        -1.07569203, -0.28269974, -1.03115629,  0.62746339, -0.3109653 ,
        -0.6643898 , -0.87369675, -0.41063571, -0.31503629, -1.26056892],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.01808192,  0.        ,  0.        , -0.46156414,  0.12732165,
         0.        ,  0.08572634,  1.03101272,  0.16683084,  1.23870985,
        -0.48228589, -0.36937906, -0.00966456, -0.15422035, -0.25473673,
         0.54697025, -0.33037559, -0.18824584, -0.11305336, -0.49345904],
       [-0.60828747,  0.        , -0.46156414,  0.        , -0.16956108,
         0.        , -0.23816134, -0.38739781, -

In [5]:
A = A.T
n = A.shape[0]

connected_idx = np.where(np.sum(A, axis = 0) != 0)[0]
n = len(connected_idx)
M = np.zeros((n,n))
for i in range(n): 
    ii = connected_idx[i]
    A_sum = np.sum(A[connected_idx,ii])
    if A_sum == 0:
        M[:,i] = A[connected_idx,ii]
        print('dangling nodes for page rank')
    else:
        M[:,i] = A[connected_idx,ii]/A_sum



In [6]:
M.shape

(18, 18)

In [10]:
#taken from da wikipedia
eps = 0.001
d = 0.85

#new and fast
v = np.random.rand(n, 1)
v = v / np.linalg.norm(v, 1)
err = 1
while err > eps:
    print(err)
    v0 = v.copy()
    v = (d * M) @ v0 + (1 - d) / n
    err = np.linalg.norm(v - v0, 2)
    
connected_scores = v.flatten()

if n != A.shape[0]:
    scores = np.zeros(A.shape[0])
    scores[connected_idx] = connected_scores

1
0.4893334960883263
0.14334636678053383
0.15337166368572425
0.04358648726418753
0.037967350125605676
0.012119678229159474
0.009428472849319117
0.003356085342439329
0.0023266693061634565


In [11]:
scores

array([ 0.14250679,  0.        , -0.01130517,  0.04274842, -0.03116435,
        0.        , -0.04981063,  0.04750598,  0.14758003, -0.01609234,
        0.15998104,  0.01519752, -0.02869626, -0.02046714,  0.18637992,
        0.05709981,  0.09147021,  0.04292244,  0.11534381,  0.10879994])

In [32]:
connected_idx

array([ 0,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])